# Generated by Django 2.1.5 on 2019-02-06 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=255)),
                ('notification_read', models.BooleanField(default=False)),
                ('notification_created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_init', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_init', to=settings.AUTH_USER_MODEL)),
                ('notification_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_rec', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
