# Generated by Django 2.1.5 on 2019-02-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
