# Generated by Django 2.1.5 on 2019-02-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_target',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
