# Generated by Django 2.1.4 on 2019-01-03 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confessions',
            name='confession_upvotes',
        ),
        migrations.AddField(
            model_name='confessions',
            name='confesison_upvotes',
            field=models.ManyToManyField(related_name='confession_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
