# Generated by Django 2.1.4 on 2019-01-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile_profile_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confessions',
            old_name='confession_created_at',
            new_name='date_created_at',
        ),
    ]
