# Generated by Django 2.1.4 on 2018-12-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_confessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='confessions',
            name='confession_upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
