# Generated by Django 2.1.4 on 2019-01-03 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190103_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confessions',
            old_name='confesison_upvotes',
            new_name='confession_upvotes',
        ),
    ]
