# Generated by Django 2.1.4 on 2018-12-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_confessions_confession_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='confessions',
            name='confession_views',
            field=models.IntegerField(default=0),
        ),
    ]
