# Generated by Django 2.1.4 on 2019-01-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190125_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_nickname',
            field=models.CharField(max_length=35),
        ),
    ]
