# Generated by Django 2.1.4 on 2019-01-03 03:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_confessions_confession_upvotes_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='confessions',
            name='confession_downvotes',
            field=models.ManyToManyField(related_name='confession_downvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
