# Generated by Django 2.1.4 on 2019-01-03 03:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_confessions_confession_downvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confessions',
            name='confession_downvotes',
            field=models.ManyToManyField(blank=True, related_name='confession_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='confessions',
            name='confession_upvotes',
            field=models.ManyToManyField(blank=True, related_name='confession_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
