# Generated by Django 2.1.4 on 2019-01-14 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_body', models.TextField()),
                ('answer_created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_created_at', models.DateTimeField(auto_now_add=True)),
                ('follow_init', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_init', to=settings.AUTH_USER_MODEL)),
                ('follow_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_rec', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', models.TextField()),
                ('question_created_at', models.DateTimeField(auto_now_add=True)),
                ('question_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_author', to=settings.AUTH_USER_MODEL)),
                ('question_directed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_directed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answerpost',
            name='answer_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='uprofile.QuestionPost'),
        ),
    ]
