# Generated by Django 2.1.4 on 2019-01-14 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpost',
            name='answer_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answerpost',
            name='answer_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uprofile.QuestionPost'),
        ),
        migrations.AlterField(
            model_name='questionpost',
            name='question_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionpost',
            name='question_directed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directed_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
