# Generated by Django 2.1.4 on 2019-01-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0002_auto_20190114_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionpost',
            old_name='question_created_at',
            new_name='date_created_at',
        ),
    ]
